import assert from 'node:assert/strict';
import { test } from 'node:test';
import fs from 'node:fs/promises';
import path from 'node:path';
import { startDatabase } from './database-fixture.mjs';
import { createInvite, authenticate } from '../api/accounts.mjs';
import { digest } from '../api/database.mjs';
import { createTask, registerWorker, pollWorker, rerunTask, recoverTask, stepResult } from '../api/tasks.mjs';
import { prepareArtifact, workspaceMaintenance } from '../api/workspace-iteration.mjs';

test('revision/recovery identity, task-scoped blob reuse, maintenance fence and worker capability roll forward together', async t => {
  const fixture = await startDatabase(); t.after(() => fixture.close()); const db = fixture.db;
  const account = await authenticate(db, { username: 'iteration-owner', password: 'fixture-password-123', code: await createInvite(db) }, { register: true, maxUsers: 10 });
  const worker = { worker_id: 'iteration-worker' }, userId = account.user.userId;
  await db.query('INSERT INTO workers(worker_id,token_hash) VALUES($1,$2)', [worker.worker_id, digest('fixture')]);
  await db.query('INSERT INTO user_worker_bindings(user_id,worker_id) VALUES($1,$2)', [userId, worker.worker_id]);
  const task = await createTask(db, userId, { objective: 'A game' });
  const bootId = 'boot-fixture';
  await registerWorker(db, worker, { protocol: 2, bootId, capabilities: { workspaceIteration: 2 } });
  const claim = async () => (await pollWorker(db, worker, { bootId }, 60000)).job;
  const first = await claim(); assert.ok(first.revisionId);
  const identity = job => ({ taskId: task.taskId, jobId: job.jobId, bootId, leaseToken: job.leaseToken });
  const blob = path.join(fixture.root, 'payload.zip'); await fs.writeFile(blob, 'payload');
  const sha = digest('payload'), original = 'artifact-' + '1'.repeat(64);
  await db.query('INSERT INTO artifacts(artifact_id,task_id,job_id,name,content_type,storage_path,sha256,size_bytes,verified) VALUES($1,$2,$3,$4,$5,$6,$7,7,true)',
    [original, task.taskId, first.jobId, 'game.zip', 'application/zip', blob, sha]);
  await stepResult(db, worker, { ...identity(first), status: 'FAIL', stopConfirmed: true });
  await rerunTask(db, task.taskId, userId, { prompt: 'Change one material' });
  const next = await claim(); assert.notEqual(next.revisionId, first.revisionId); assert.equal(next.parentRevisionId, first.revisionId);
  assert.equal(next.workspaceId, first.workspaceId); assert.equal(next.budgetGrant.authorCallsPerAsset, 3);
  const metadata = { ...identity(next), name: 'game.zip', sha256: sha, sizeBytes: 7, artifactId: 'artifact-' + '2'.repeat(64) };
  const reused = await prepareArtifact(db, worker, metadata); assert.equal(reused.uploadRequired, false);
  assert.equal((await prepareArtifact(db, worker, metadata)).artifactId, reused.artifactId);
  await assert.rejects(prepareArtifact(db, worker, { ...metadata, leaseToken: 'stale' }), error => error.status === 409);
  await assert.rejects(prepareArtifact(db, worker, { ...metadata, taskId: 'another-task' }), error => error.status === 409);
  assert.equal((await db.query('SELECT storage_path FROM artifacts WHERE artifact_id=$1', [reused.artifactId])).rows[0].storage_path, blob);
  await assert.rejects(workspaceMaintenance(db, worker, { taskId: task.taskId, migrationId: 'migration', action: 'begin' }), error => error.status === 409);
  await stepResult(db, worker, { ...identity(next), status: 'FAIL', stopConfirmed: true });
  const recovery = await recoverTask(db, task.taskId, userId, { requestId: 'recovery-one' });
  assert.equal(recovery.revisionId, next.revisionId);
  assert.equal((await recoverTask(db, task.taskId, userId, { requestId: 'recovery-one' })).runId, recovery.runId);
  const ticket = await workspaceMaintenance(db, worker, { taskId: task.taskId, migrationId: 'migration', action: 'begin' });
  assert.equal(await claim(), null);
  const auth = { taskId: task.taskId, migrationId: 'migration', token: ticket.maintenance.token, writeEpoch: ticket.maintenance.writeEpoch,
    planHash: 'c'.repeat(64), workerCommit: 'b'.repeat(40) };
  await workspaceMaintenance(db, worker, { ...auth, action: 'commit' });
  await workspaceMaintenance(db, worker, { ...auth, action: 'release' });
  await registerWorker(db, worker, { protocol: 2, bootId, capabilities: {} }); assert.equal(await claim(), null);
  await registerWorker(db, worker, { protocol: 2, bootId, capabilities: { workspaceIteration: 2 } });
  const recovered = await claim(); assert.equal(recovered.revisionId, next.revisionId); assert.equal(recovered.runId, recovery.runId);
  await stepResult(db, worker, { ...identity(recovered), status: 'FAIL', stopConfirmed: true });
});
